//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.2-hudson-jaxb-ri-2.2-63- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.12.08 at 03:34:25 PM CET 
//


package org.escidoc.core.domain.sru;

import javax.xml.bind.JAXBElement;
import javax.xml.namespace.QName;

public class ExplainResponseTO
    extends JAXBElement<ExplainResponseType>
{

    protected final static QName NAME = new QName("http://www.loc.gov/zing/srw/", "explainResponse");

    public ExplainResponseTO(ExplainResponseType value) {
        super(NAME, ((Class) ExplainResponseType.class), null, value);
    }

    public ExplainResponseTO() {
        super(NAME, ((Class) ExplainResponseType.class), null, null);
    }

}
