//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.2-hudson-jaxb-ri-2.2-63- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.12.08 at 03:34:25 PM CET 
//


package org.escidoc.core.domain.sru;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import org.apache.axis.types.PositiveInteger;


/**
 * <p>Java class for searchRetrieveRequestType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="searchRetrieveRequestType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.loc.gov/zing/srw/}requestType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.loc.gov/zing/srw/}query"/>
 *         &lt;element ref="{http://www.loc.gov/zing/srw/}startRecord" minOccurs="0"/>
 *         &lt;element ref="{http://www.loc.gov/zing/srw/}maximumRecords" minOccurs="0"/>
 *         &lt;element ref="{http://www.loc.gov/zing/srw/}recordPacking" minOccurs="0"/>
 *         &lt;element ref="{http://www.loc.gov/zing/srw/}recordSchema" minOccurs="0"/>
 *         &lt;element ref="{http://www.loc.gov/zing/srw/}recordXPath" minOccurs="0"/>
 *         &lt;element ref="{http://www.loc.gov/zing/srw/}resultSetTTL" minOccurs="0"/>
 *         &lt;element ref="{http://www.loc.gov/zing/srw/}sortKeys" minOccurs="0"/>
 *         &lt;element ref="{http://www.loc.gov/zing/srw/}stylesheet" minOccurs="0"/>
 *         &lt;element ref="{http://www.loc.gov/zing/srw/}extraRequestData" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "searchRetrieveRequestType", propOrder = {
    "query",
    "startRecord",
    "maximumRecords",
    "recordPacking",
    "recordSchema",
    "recordXPath",
    "resultSetTTL",
    "sortKeys",
    "stylesheet",
    "extraRequestData"
})
public class SearchRetrieveRequestType
    extends RequestType
    implements Serializable
{

    @XmlElement(required = true)
    protected String query;
    @XmlElement(type = String.class, defaultValue = "1")
    @XmlJavaTypeAdapter(Adapter8 .class)
    @XmlSchemaType(name = "positiveInteger")
    protected PositiveInteger startRecord;
    @XmlElement(type = String.class)
    @XmlJavaTypeAdapter(Adapter9 .class)
    @XmlSchemaType(name = "nonNegativeInteger")
    protected org.apache.axis.types.NonNegativeInteger maximumRecords;
    protected String recordPacking;
    protected String recordSchema;
    protected String recordXPath;
    @XmlElement(type = String.class)
    @XmlJavaTypeAdapter(Adapter6 .class)
    @XmlSchemaType(name = "nonNegativeInteger")
    protected org.apache.axis.types.NonNegativeInteger resultSetTTL;
    protected String sortKeys;
    @XmlSchemaType(name = "anyURI")
    protected String stylesheet;
    protected ExtraDataType extraRequestData;

    /**
     * Gets the value of the query property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQuery() {
        return query;
    }

    /**
     * Sets the value of the query property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQuery(String value) {
        this.query = value;
    }

    /**
     * Gets the value of the startRecord property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public PositiveInteger getStartRecord() {
        return startRecord;
    }

    /**
     * Sets the value of the startRecord property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStartRecord(PositiveInteger value) {
        this.startRecord = value;
    }

    /**
     * Gets the value of the maximumRecords property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public org.apache.axis.types.NonNegativeInteger getMaximumRecords() {
        return maximumRecords;
    }

    /**
     * Sets the value of the maximumRecords property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaximumRecords(org.apache.axis.types.NonNegativeInteger value) {
        this.maximumRecords = value;
    }

    /**
     * Gets the value of the recordPacking property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRecordPacking() {
        return recordPacking;
    }

    /**
     * Sets the value of the recordPacking property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRecordPacking(String value) {
        this.recordPacking = value;
    }

    /**
     * Gets the value of the recordSchema property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRecordSchema() {
        return recordSchema;
    }

    /**
     * Sets the value of the recordSchema property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRecordSchema(String value) {
        this.recordSchema = value;
    }

    /**
     * Gets the value of the recordXPath property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRecordXPath() {
        return recordXPath;
    }

    /**
     * Sets the value of the recordXPath property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRecordXPath(String value) {
        this.recordXPath = value;
    }

    /**
     * Gets the value of the resultSetTTL property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public org.apache.axis.types.NonNegativeInteger getResultSetTTL() {
        return resultSetTTL;
    }

    /**
     * Sets the value of the resultSetTTL property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResultSetTTL(org.apache.axis.types.NonNegativeInteger value) {
        this.resultSetTTL = value;
    }

    /**
     * Gets the value of the sortKeys property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSortKeys() {
        return sortKeys;
    }

    /**
     * Sets the value of the sortKeys property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSortKeys(String value) {
        this.sortKeys = value;
    }

    /**
     * Gets the value of the stylesheet property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStylesheet() {
        return stylesheet;
    }

    /**
     * Sets the value of the stylesheet property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStylesheet(String value) {
        this.stylesheet = value;
    }

    /**
     * Gets the value of the extraRequestData property.
     * 
     * @return
     *     possible object is
     *     {@link ExtraDataType }
     *     
     */
    public ExtraDataType getExtraRequestData() {
        return extraRequestData;
    }

    /**
     * Sets the value of the extraRequestData property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExtraDataType }
     *     
     */
    public void setExtraRequestData(ExtraDataType value) {
        this.extraRequestData = value;
    }

}
