//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.02.09 at 03:25:44 PM CET 
//


package de.escidoc.core.domain.sru.extradata;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for extraData element declaration.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;element name="extraData">
 *   &lt;complexType>
 *     &lt;complexContent>
 *       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *         &lt;sequence>
 *           &lt;element name="databaseTitle" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *           &lt;element name="targetURL" type="{http://oclc.org/srw/extraData/}targetURLType" minOccurs="0"/>
 *         &lt;/sequence>
 *       &lt;/restriction>
 *     &lt;/complexContent>
 *   &lt;/complexType>
 * &lt;/element>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "databaseTitle",
    "targetURL"
})
@XmlRootElement(name = "extraData")
public class ExtraDataTO
    implements Serializable
{

    @XmlElement(required = true)
    protected String databaseTitle;
    protected TargetUrlTO targetURL;

    /**
     * Gets the value of the databaseTitle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDatabaseTitle() {
        return databaseTitle;
    }

    /**
     * Sets the value of the databaseTitle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDatabaseTitle(String value) {
        this.databaseTitle = value;
    }

    /**
     * Gets the value of the targetURL property.
     * 
     * @return
     *     possible object is
     *     {@link TargetUrlTO }
     *     
     */
    public TargetUrlTO getTargetURL() {
        return targetURL;
    }

    /**
     * Sets the value of the targetURL property.
     * 
     * @param value
     *     allowed object is
     *     {@link TargetUrlTO }
     *     
     */
    public void setTargetURL(TargetUrlTO value) {
        this.targetURL = value;
    }

}
